export const blogs = [
  {
    title: "Real Madrid Prepare for Key Decisions Ahead of 2025–26 Season",
    date: "2025-07-31",
    author: "Real Madrid Insider Desk",
    category: "Club Update",
    team: "Real Madrid",
    opponent: null,
    location: null,
    summary:
      "Real Madrid face a crucial period ahead of the new season, with important developments involving player contracts, squad roles, and transfer plans.",
    content: [
      "Vinícius Jr. remains committed to Real Madrid despite contract renewal talks being temporarily paused. He has rejected multiple offers from Saudi clubs and is expected to stay until at least 2027. The club anticipates a final extension to be agreed in 2026.",
      "Endrick has declined all loan proposals, choosing instead to compete for a first-team role under new manager Xabi Alonso. He aims to earn the number 9 shirt this season.",
      "Gonzalo García, another young striker from the academy, is also pushing for the number 9 role after an impressive showing in the Club World Cup. A healthy competition is expected between him and Endrick.",
      "New signing Franco Mastantuono from River Plate is being fast-tracked into the first-team setup. The club sees him as ready for immediate contribution rather than a long-term project.",
      "Real Madrid are closely monitoring Premier League midfielders Kobbie Mainoo and Adam Wharton. While interest is genuine, the club's leadership is cautious about making additional signings this summer.",
      "Rodrygo has drawn interest from Tottenham, Liverpool, and Newcastle. However, his high wages make a permanent move unlikely. A loan is being considered if a strong offer arrives.",
      "Jacobo Ramón has officially joined Serie A side Como. Real Madrid have included several buy-back clauses, allowing them future options to re-sign the player.",
    ],
    key_points: [
      "Vinícius Jr. expected to extend contract in 2026",
      "Endrick rejects loan and aims for a first-team role",
      "Number 9 shirt competition between Endrick and Gonzalo García",
      "Franco Mastantuono set for early first-team inclusion",
      "Madrid monitoring Kobbie Mainoo and Adam Wharton",
      "Rodrygo transfer interest continues; loan more likely than sale",
      "Jacobo Ramón joins Como with buy-back options in place",
    ],
    quote:
      "Both Endrick and Gonzalo are ready to lead the line. This is a new age for the club’s attack.",
    quote_by: "Club sources",
    stats: {
      possession: null,
      shots_on_target: null,
      corners: null,
    },
    tags: [
      "Real Madrid",
      "Vinícius Jr.",
      "Endrick",
      "Gonzalo García",
      "Franco Mastantuono",
      "Rodrygo",
      "Kobbie Mainoo",
      "Adam Wharton",
      "Jacobo Ramón",
      "Xabi Alonso",
    ],
  },
  {
    title:
      "Liverpool Confirm Luis Díaz Exit & Eye Alexander Isak Amid Youth Signings",
    date: "2025-07-31",
    author: "Liverpool Insider News Desk",
    category: "Transfer Update",
    team: "Liverpool",
    opponent: null,
    location: null,
    summary:
      "Liverpool have sold Luis Díaz to Bayern Munich and are targeting striker Alexander Isak while securing youth talent and extending contracts.",
    content: [
      "Liverpool have officially completed the £65.5 million transfer of Luis Díaz to Bayern Munich, raising over £190 million in player sales since mid‑2024 under sporting director Richard Hughes :contentReference[oaicite:1]{index=1}.",
      "Manager Arne Slot paid tribute to Díaz’s work ethic and influence at the club, noting he will be missed for both his personality and his dressing‑room song :contentReference[oaicite:2]{index=2}.",
      "Liverpool are now prioritizing a move for Newcastle striker Alexander Isak, who has expressed his intention to leave and is training at Real Sociedad while Liverpool negotiate a fee of around £120 million :contentReference[oaicite:3]{index=3}.",
      "Young forward Will Wright has agreed personal terms with Liverpool ahead of a move from Salford City, beating competition from Arsenal for the signing of the 17‑year‑old :contentReference[oaicite:4]{index=4}.",
      "Liverpool FC Women star Mia Enderby has signed a new contract, committing her future to the club as an England U23 international at just 20 years old :contentReference[oaicite:5]{index=5}.",
    ],
    key_points: [
      "Luis Díaz sold to Bayern Munich for £65.5 M",
      "Arne Slot praises Díaz’s impact on and off the field",
      "Liverpool pushing for a deal to sign Alexander Isak (~£120 M)",
      "Will Wright deal finalized with Salford City for youth prospect",
      "Mia Enderby extends contract with Liverpool FC Women",
    ],
    quote: "I’ll miss the person, the player and the song.",
    quote_by: "Arne Slot",
    stats: {
      possession: null,
      shots_on_target: null,
      corners: null,
    },
    tags: [
      "Liverpool",
      "Luis Díaz",
      "Alexander Isak",
      "Transfer Window",
      "Will Wright",
      "Mia Enderby",
      "Arne Slot",
    ],
  },
  {
    title: "PSG Dominate Marseille in Le Classique With Mbappé Brace",
    date: "2025-07-31",
    author: "L'Équipe Sports Desk",
    category: "Match Report",
    team: "Paris Saint-Germain",
    opponent: "Marseille",
    location: "Parc des Princes, Paris",
    summary:
      "Paris Saint-Germain delivered a commanding 3-0 victory over arch-rivals Marseille, with Kylian Mbappé scoring twice in a fiery Le Classique clash.",
    content: [
      "Paris Saint-Germain showed their dominance in the French top flight with a convincing 3-0 win over Olympique de Marseille at the Parc des Princes.",
      "Kylian Mbappé opened the scoring in the 14th minute with a thunderous strike from outside the box. He added a second goal just after halftime following a brilliant solo run, taking his tally to 11 goals this season.",
      "Marseille struggled to cope with PSG's pressing and creativity, and the hosts sealed the victory in the 76th minute through Ousmane Dembélé, who converted a low cross from Achraf Hakimi.",
      "The win keeps PSG at the top of the Ligue 1 table as they continue their unbeaten start under new manager Luis Enrique.",
    ],
    key_points: [
      "Kylian Mbappé scored his 10th and 11th league goals of the season.",
      "Ousmane Dembélé scored his first goal since joining PSG.",
      "PSG are unbeaten in their last 12 Ligue 1 matches.",
      "Luis Enrique praised the team’s discipline and attacking intent.",
    ],
    quote:
      "We played with intensity, intelligence, and passion. It’s a performance that defines what we want this team to be.",
    quote_by: "Luis Enrique",
    stats: {
      possession: {
        psg: "65%",
        marseille: "35%",
      },
      shots_on_target: {
        psg: 8,
        marseille: 2,
      },
      corners: {
        psg: 9,
        marseille: 3,
      },
    },
    tags: [
      "PSG",
      "Marseille",
      "Ligue 1",
      "Kylian Mbappé",
      "Luis Enrique",
      "Le Classique",
      "Match Report",
    ],
  },
  {
    title:
      "Real Madrid Clinch Late Winner Against Atletico in Madrid Derby Thriller",
    date: "2025-07-31",
    author: "Marca Football Staff",
    category: "Match Report",
    team: "Real Madrid",
    opponent: "Atletico Madrid",
    location: "Santiago Bernabéu, Madrid",
    summary:
      "Real Madrid secured a dramatic 2-1 win over city rivals Atletico Madrid with a late goal from Jude Bellingham, keeping their La Liga title hopes alive.",
    content: [
      "Real Madrid came out on top in a fiercely contested Madrid Derby, defeating Atletico 2-1 at the Santiago Bernabéu in front of a roaring home crowd.",
      "Atletico took an early lead through Antoine Griezmann in the 12th minute, but Los Blancos responded before the break, with Vinícius Jr. equalizing after a clever one-two with Rodrygo.",
      "The match remained finely balanced until the 89th minute when Jude Bellingham found space at the edge of the box and smashed in the winner, sending the Bernabéu into jubilation.",
      "With the victory, Real Madrid maintain their unbeaten home record this season and stay in close contention at the top of the La Liga table.",
    ],
    key_points: [
      "Jude Bellingham scored his 8th goal of the season and the game-winner.",
      "Vinícius Jr. was influential with a goal and strong attacking presence.",
      "Real Madrid remain unbeaten at home this La Liga season.",
      "Carlo Ancelotti praised the team's patience and fighting spirit.",
    ],
    quote:
      "These games are decided by moments. Jude gave us the moment we needed. It was a deserved win.",
    quote_by: "Carlo Ancelotti",
    stats: {
      possession: {
        real_madrid: "59%",
        atletico_madrid: "41%",
      },
      shots_on_target: {
        real_madrid: 6,
        atletico_madrid: 4,
      },
      corners: {
        real_madrid: 5,
        atletico_madrid: 2,
      },
    },
    tags: [
      "Real Madrid",
      "Atletico Madrid",
      "La Liga",
      "Madrid Derby",
      "Jude Bellingham",
      "Vinícius Jr.",
      "Carlo Ancelotti",
      "Match Report",
    ],
  },
  {
    title: "Barcelona Cruise Past Sevilla With Lewandowski Double at Montjuïc",
    date: "2025-07-31",
    author: "Sport ES Newsroom",
    category: "Match Report",
    team: "Barcelona",
    opponent: "Sevilla",
    location: "Estadi Olímpic Lluís Companys, Barcelona",
    summary:
      "Barcelona returned to winning ways with a dominant 3-0 win over Sevilla, featuring a brace from Robert Lewandowski and a clean sheet for Ter Stegen.",
    content: [
      "Barcelona delivered a confident performance against Sevilla, securing a 3-0 victory in front of a packed crowd at their temporary home in Montjuïc.",
      "Robert Lewandowski opened the scoring in the 24th minute with a close-range finish after a brilliant through-ball from Pedri. The Polish striker added a second early in the second half, converting a rebound after João Félix's shot was parried.",
      "Teenage sensation Lamine Yamal added the third in the 78th minute with a composed finish after cutting in from the right wing, sealing all three points for Xavi’s side.",
      "Barcelona looked sharp throughout the game, dominating possession and limiting Sevilla to just one shot on target.",
    ],
    key_points: [
      "Robert Lewandowski scored twice, bringing his season total to 10 goals.",
      "Lamine Yamal became the youngest Barcelona player to score this season.",
      "Barcelona kept their 4th clean sheet in 6 matches.",
      "Xavi praised the team’s fluid attack and defensive organization.",
    ],
    quote:
      "This is the identity we’re working toward – intensity, movement, and total control of the ball.",
    quote_by: "Xavi Hernández",
    stats: {
      possession: {
        barcelona: "66%",
        sevilla: "34%",
      },
      shots_on_target: {
        barcelona: 9,
        sevilla: 1,
      },
      corners: {
        barcelona: 8,
        sevilla: 2,
      },
    },
    tags: [
      "Barcelona",
      "Sevilla",
      "La Liga",
      "Robert Lewandowski",
      "Lamine Yamal",
      "Xavi Hernández",
      "Match Report",
    ],
  },
  {
    title: "City News Unfold: O’Reilly Extension & FFP Charges Update",
    date: "2025-07-31",
    author: "City Insider News Desk",
    category: "Club Update",
    team: "Manchester City",
    opponent: null,
    location: null,
    summary:
      "Manchester City confirm contract extension for rising star Nico O’Reilly amid ongoing Premier League financial fair play charges.",
    content: [
      "Manchester City have agreed a new contract extension with youngster Nico O’Reilly, who impressed last season primarily as a left-back and is now seen as a future midfielder for Pep Guardiola’s squad :contentReference[oaicite:1]{index=1}.",
      "Meanwhile, Richard Masters, CEO of the Premier League, addressed the more than 130 financial fair play charges against City, stating that the verdict is expected to take until at least October and remains confidential :contentReference[oaicite:2]{index=2}.",
      "Erling Haaland voiced confidence that City will successfully defend themselves, reinforcing his belief after signing a long-term deal earlier this year :contentReference[oaicite:3]{index=3}.",
      "Club director Txiki Begiristain has departed following a trophy-less 2024–25 season and amid the FFP controversy facing the club :contentReference[oaicite:4]{index=4}.",
    ],
    key_points: [
      "Nico O’Reilly signs new contract extension—City reject bids from Leverkusen",
      "City facing 130 alleged FFP breaches with hearing verdict potentially delayed until October",
      "Erling Haaland believes in club’s innocence and backs the new contract signings",
      "Director Txiki Begiristain leaves in wake of season outcome and off-field issues",
    ],
    quote:
      "I trust the club completely. We’re doing things the right way and we’ll see it through,”",
    quote_by: "Erling Haaland",
    stats: {
      possession: null,
      shots_on_target: null,
      corners: null,
    },
    tags: [
      "Manchester City",
      "Nico O’Reilly",
      "Financial Fair Play",
      "Erling Haaland",
      "Txiki Begiristain",
      "Premier League",
    ],
  },
];
